import Navbar from '@/Components/Navbar';
import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const myNavbarFont = localFont({
  src: '../public/fonts/AlikeAngular-Regular.ttf',
  variable: '--font-navbar-custom', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myNavbarFont.variable} antialiased bg-fixed bg-cover bg-center`}
        style={{ backgroundImage: "url('/parchment2.png')", backgroundAttachment: 'fixed', minHeight: '100vh' }}>
        <Navbar />
          {children}
      </body>
    </html>
  );
}
